#  Copyright (c) 2021 Cristian Patrasciuc. All rights reserved.
#  Use of this source code is governed by a BSD-style license that can be
#  found in the LICENSE file.

name: Build MacOS App Bundle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-app.txt
          pip install -r requirements-packaging.txt
          python -m pip install --upgrade Pillow
      - name: Build Cython modules
        run: |
          cd src && python setup.py build_ext --inplace --force
      - name: Build the MacOS app bundle and zip it.
        run: |
          python -OO -m PyInstaller --clean -y main.spec
          cd dist
          filename=`find * -perm +111 -type f -maxdepth 1 -print`
          zip $filename.zip $filename.app -r
          echo ARTIFACT_FILE_NAME=$filename > $GITHUB_ENV
      - name: Upload artifact (ZIP)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_FILE_NAME }}.zip
          path: dist/${{ env.ARTIFACT_FILE_NAME }}.zip
      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_FILE_NAME }}
          path: dist/${{ env.ARTIFACT_FILE_NAME }}
